---
- name: Clone repository
  git:
    repo=https://github.com/EdReeves/cumulus.git
    dest={{cumulus_root}}
    version=dev
  register: repo_cloned
- name: Link repository to site root
  when: repo_cloned|success
  file:
    src=/var/lib/cumulus/src/www
    dest={{nginx_root}}
    state=link
- name: Composer install
  command: composer install
  args:
    chdir: "{{cumulus_root}}"